@ call node_modules\.bin\browserify public\javascripts\requestLogin.js > public\javascripts\_login_bundle.js
@ call node_modules\.bin\browserify public\javascripts\requestSignup.js > public\javascripts\_signup_bundle.js
@ call node_modules\.bin\browserify public\javascripts\session.js > public\javascripts\_session_bundle.js
@ call node_modules\.bin\browserify public\javascripts\commonSession.js > public\javascripts\_commonSession_bundle.js
@ call node_modules\.bin\browserify public\javascripts\listForums.js > public\javascripts\_listForums_bundle.js
@ call node_modules\.bin\browserify public\javascripts\logout.js > public\javascripts\_logout_bundle.js
@ call node_modules\.bin\browserify public\javascripts\listThreads.js > public\javascripts\_listThreads_bundle.js
@ call node_modules\.bin\browserify public\javascripts\loadThread.js > public\javascripts\_loadThread_bundle.js
@ call node_modules\.bin\browserify public\javascripts\createThread.js > public\javascripts\_createThread_bundle.js
@ call node_modules\.bin\browserify public\javascripts\createPost.js > public\javascripts\_createPost_bundle.js
@ call node_modules\.bin\browserify public\javascripts\admin.js > public\javascripts\_admin_bundle.js
@ call node_modules\.bin\browserify public\javascripts\adminSession.js > public\javascripts\_adminSession_bundle.js
@ call node_modules\.bin\browserify public\javascripts\adminLogin.js > public\javascripts\_adminLogin_bundle.js
